services:
  web:
    image: python:3.12-slim
    container_name: librecourse_web
    command: python dev_jumpstart.py
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8081:8000"
    environment:
      DJANGO_PORT: 8000
    tty: true
