services:
  web:
    image: python:3.12-slim
    container_name: librecourse_web
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8081:8000"
    environment:
      DJANGO_PORT: 8000
    command: |
      bash -c "
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    stdin_open: true
    tty: true