name: "Bug Report"
description: Report a bug or unexpected behavior
title: "Bug: <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below to help us investigate and fix the issue.
  
  - type: input
    id: bug_summary
    attributes:
      label: "Bug Summary"
      placeholder: "e.g. Application crashes when submitting empty form"
    validations:
      required: true
  
  - type: textarea
    id: bug_description
    attributes:
      label: "Detailed Description"
      description: "Provide a clear and detailed description of what the bug is."
      placeholder: "Explain what happened and what you expected to happen..."
    validations:
      required: true
  
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide step-by-step instructions to reproduce the bug."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe the expected outcome..."
    validations:
      required: true
  
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe what actually occurred..."
    validations:
      required: true
  
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots/Logs"
      description: "If applicable, add screenshots or error logs to help explain the problem."
      placeholder: "Paste screenshots or logs here..."
    validations:
      required: false
  
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is this bug?"
      options:
        - "Critical (blocks core functionality)"
        - "High (major feature broken)"
        - "Medium (feature partially broken)"
        - "Low (minor issue or cosmetic)"
    validations:
      required: true
  
  - type: input
    id: environment_os
    attributes:
      label: "Operating System"
      placeholder: "e.g. Windows 11, macOS 14.2, Ubuntu 22.04"
    validations:
      required: true
  
  - type: input
    id: environment_browser
    attributes:
      label: "Browser"
      placeholder: "e.g. Chrome 120, Firefox 121, Safari 17"
    validations:
      required: true
  
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
      placeholder: "Any additional information that might be helpful..."
    validations:
      required: false
  
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have searched existing issues to ensure this bug hasn't been reported"
          required: true
        - label: "I have provided all required information above"
          required: true
        - label: "I can reproduce this bug consistently"
          required: false