# Generated by Django 4.2.24 on 2025-09-15 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0003_pendingcollaborator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pendingcollaborator",
            name="invited_at",
        ),
        migrations.AddField(
            model_name="pendingcollaborator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pendingcollaborator",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendingcollaborator",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
